name: '📌 Feature'
description: '새로운 기능 또는 명세가 있나요?'
title: '[Feature] '
labels: '📌 feature'
body:
  - type: textarea
    attributes:
      label: Task Description
      placeholder: 새로운 기능에 대한 설명을 작성해 주세요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: ETC
      placeholder: 추가 전달 사항이 있다면 작성해 주세요.
