name: '🧩 Refactor'
description: '리팩터링을 해야할 부분이 있나요?'
title: '[Refactor] '
labels: '🧩 refactor'
body:
  - type: textarea
    attributes:
      label: Task Description
      placeholder: 리팩토링에 대한 설명을 작성해 주세요 (+리팩토링 이유).
    validations:
      required: true
  - type: textarea
    attributes:
      label: ETC
      placeholder: 추가 전달 사항이 있다면 작성해 주세요.
